version: '3'

networks:
  app:
    driver: bridge
  web:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: web3-nginx
    environment:
       - HOST=${HOST}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    networks:
      - web
    restart: always
    # stdin_open: true
    tty: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - ./nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key:ro
      - ./nginx/logs:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_host
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/ipfs_data:/data/ipfs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '4001:4001'
      - '4001:4001/udp'
      - '8080:8080'
      - '5001:5001'
  db:
    image: mariadb:10.6
    container_name: web3-mariadb
    networks:
      - app
    env_file:
      - ./Backend/.env
    restart: always
    volumes:
      - ./Backend/mysql/data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  phpmyadmin:
    image: phpmyadmin
    container_name: web3-phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - db
    restart: always
    networks:
      - app
    env_file:
      - ./Backend/.env
    environment:
      PMA_HOST: db
      # PMA_USER: ${DB_USERNAME}
      # PMA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  backend:
    image: a20688392/ipfs-blog-backend:0.0.1-old
    container_name: web3-backend
    command: /bin/sh -c "sh /app/migration-entrypoint.sh"
    networks:
      - app
      - web
    env_file:
      - ./Backend/.env
    environment:
      DB_HOST: db
    depends_on:
      - db
      - ipfs
    volumes:
      - ./Backend/outputs:/app/outputs
      - ./Backend/logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  frontend:
    container_name: web3-frontend
    build:
      dockerfile: Dockerfile
      context: ./Frontend
      target: production
    env_file:
      - ./Frontend/.env
    networks:
      - web
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro